### PR TITLE
clean up iterator interface; added iterator tests

### PR DESCRIPTION
**Pull request by Teque5**
New and improved!

- read from file using `read_samples()` to correctly retrieve multichannel data
- add tests for iterator interface

This is the one.

### CODE REVIEW

**Comment by Teque5** [comment]
Okay i'm all done messing with the commit history. If you are cool with this I think it's ready.

**Comment by Teque5** [comment]
Are you happy with this instantiation?

**Comment by gmabey** [comment]
@Teque5 I apologize but only just now realized that I'm not subscribed to changes in my own fork :-/ .  I promise I'll see this through this week.

**Comment by gmabey** [comment]
So, I still am not in love with how you removed `SigMFFileIterator` but I have to admit that it's cleaner to not have it, and my counter example of where it would fail is pretty remote, although not as remote as say the planet Hoth.

I do appreciate that you added the tests and whatnot, and I will defer to your position as an actual maintainer of SigMF.  Basically, it's not worth fighting over, we got bigger fish to fry.

I am going to revert that 1.0.2 change though (after I merge your PR ... hmm maybe there's a better way to do that?) as I think things got a bit increment happy there.

**Pull request merged**
